name: Build Python Zip

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  python-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.9'
    - name: Build Python zip
      run: python3 get_deps.py
    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: python_zip
        path: |
          ./*.zip